<?php
return [

    'main' => [
            'title' =>  'موسسه زبان',
            'status' =>  '1',
            'meta_keywords' =>  'زبان، اموزش، زبان انگلیسی',
            'meta_description' =>  'موسسه اموزش زبان',
        ],
    'about_us' => [
            'introduction' =>  'این متن ازمایشی است',
            'email' =>  'info@zaban.com',
            'telegram' =>  'https://telegram.me/test.org',
            'instagram' =>  'https://www.instagram.com/test.org',
            'facebook' =>  'https://www.facebook.com/test.org',
            'google_plus' =>  'https://plus.google.com/+test.org',
            'twitter' =>  'https://twitter.com/test.org',
            'phone' =>  '0098253700000',
            'fax' =>  '009823000000',
            'address' =>  '  ایران ـ قم ـ ...',
            'longitude' =>  '000',
            'latitude' =>  '000',
        ],
    'user' => [
            'avatar_size' =>  '500',
            'avatar_width' =>  '250',
            'avatar_height' =>  '250',
            'avatar_extension' =>  'jpg, jpeg, png',
            'avatar_destination' =>  'users/avatar/',
        ],
    'content' => [
            'logo_size' =>  '500',
            'logo_width' =>  '250',
            'logo_height' =>  '250',
            'logo_extension' =>  'jpg, jpeg, png',
            'logo_destination' =>  'content/logo/',
            'image_size' =>  '500',
            'image_width' =>  '700',
            'image_height' =>  '450',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'content/image/',
        ],
    'page' => [
            'image_size' =>  '500',
            'image_width' =>  '200',
            'image_height' =>  '278',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'page/image/',
        ],
    'course' => [
            'image_size' =>  '500',
            'image_width' =>  '700',
            'image_height' =>  '450',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'course/image/',
        ],
    'class_room' => [
            'image_size' =>  '500',
            'image_width' =>  '700',
            'image_height' =>  '450',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'class_room/image/',
        ],
    'slider' => [
            'image_size' =>  '500',
            'image_width' =>  '700',
            'image_height' =>  '450',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'slider/image/',
        ],

'available_langs'=>['fa','en','ar'],
];
