<?php
return [

    'main' => [
            'title' =>  'ProfsAdvice',
            'related_sections' =>  'courses,translations,other',
            'status' =>  '1',
            'meta_keywords' =>  'زبان، آموزش، زبان انگلیسی',
            'meta_description' =>  'موسسه اموزش زبان',
            'footer_tags' =>  'English,Editing,Translation,Design',
            'developer_name' =>  'Rahbod',
            'fa_title' =>  'موسسه زبان',
            'box_title' =>  'translate your documents with us',
            'box_subtitle' =>  'off 10-50%',
            'box_description' =>  'If you’re looking for a truly precise translator with cool history,here you will see what you are searching for',
            'box_link_title' =>  'Login | Register',
            'box_link_url' =>  'http://www.profsadvice.com/en/login',
            'box_image_url' =>  'http://profsadvice.ir/storage/attachment/KING%2037%201920x1280%20(3).jpg?_t=1592844335',
            'site_logo' =>  'http://profsadvice.ir/storage/attachment/site_logo.png?_t=1592847376',
        ],
    'about_us' => [
            'introduction' =>  'این متن ازمایشی است',
            'email' =>  'info@zaban.com',
            'telegram' =>  'https://telegram.me/test.org',
            'instagram' =>  'https://www.instagram.com/test.org',
            'whatsapp' =>  'https://www.whatsapp.com/test.org',
            'linked_in' =>  'https://linked-in.com/test.org',
            'twitter' =>  'https://twitter.com/test.org',
            'phone' =>  '0098253700000',
            'fax' =>  '009823000000',
            'address' =>  'Iran - Tehran',
            'longitude' =>  '000',
            'latitude' =>  '000',
        ],
    'user' => [
            'avatar_size' =>  '500',
            'avatar_width' =>  '250',
            'avatar_height' =>  '250',
            'avatar_extension' =>  'jpg, jpeg, png',
            'avatar_destination' =>  'users/avatar/',
        ],
    'content' => [
            'logo_size' =>  '1024',
            'logo_width' =>  '550',
            'logo_height' =>  '550',
            'logo_extension' =>  'jpg, jpeg, png',
            'logo_destination' =>  'content/logo/',
            'image_size' =>  '2048',
            'image_width' =>  '800',
            'image_height' =>  '550',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'content/image/',
        ],
    'page' => [
            'image_size' =>  '5120',
            'image_width' =>  '200',
            'image_height' =>  '278',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'page/image/',
        ],
    'course' => [
            'image_size' =>  '2048',
            'image_width' =>  '800',
            'image_height' =>  '550',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'course/image/',
        ],
    'class_room' => [
            'image_size' =>  '5000',
            'image_width' =>  '700',
            'image_height' =>  '450',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'class_room/image/',
        ],
    'slider' => [
            'image_size' =>  '5000',
            'image_width' =>  '2000',
            'image_height' =>  '767',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'slider/image/',
        ],
    'translate_request' => [
            'translated_file_size' =>  '5000',
            'translated_file_extension' =>  'doc,docx,pdf,zip,rar',
            'translated_file_destination' =>  'translate_request/',
        ],
    'attachment' => [
            'attachment_size' =>  '5000',
            'attachment_extension' =>  'doc,docx,pdf,zip,rar,txt,jpeg,jpg,png,svg',
            'attachment_destination' =>  'attachment/',
        ],

'available_langs'=>['fa','en','ar'],
];
